const COUNTRIES = [
  // ─── ASIA ──────────────────────────────────────────────

  {id:"Japan", name:"Japan", flag:"🇯🇵",
    img:"img/japan.jpg",
    continent:"Asia", desc:"Cherry blossoms, Mount Fuji, ancient shrines and Tokyo neon lights",
    price:1800, rating:5, tags:["Culture","Food","Temples","Modern"], visa:"eVisa", best:"Mar–May, Oct–Nov" },
  { name:"Thailand", flag:"🇹🇭",
    img:"img/thailand.jpg",
    continent:"Asia", desc:"Golden temples, tropical islands, street food paradise and turquoise seas",
    price:600, rating:5, tags:["Beach","Food","Budget","Temples"], visa:"Visa on Arrival", best:"Nov–Feb" },
  { name:"India", flag:"🇮🇳",
    img:"img/tajmahal.jpg",
    continent:"Asia", desc:"Taj Mahal, ancient temples, vibrant festivals, spices and diverse cultures",
    price:400, rating:5, tags:["Heritage","Food","Culture","Budget"], visa:"eVisa", best:"Oct–Mar" },
  { name:"Maldives", flag:"🇲🇻",
    img:"img/maldives.jpg",
    continent:"Asia", desc:"Overwater villas, crystal lagoons, coral reefs and total island seclusion",
    price:3500, rating:5, tags:["Luxury","Beach","Diving","Honeymoon"], visa:"Free on Arrival", best:"Nov–Apr" },
  { name:"Indonesia (Bali)", flag:"🇮🇩",
    img:"img/indonesia.jpg",
    continent:"Asia", desc:"Terraced rice fields, Hindu temples, surf breaks and jungle retreats",
    price:700, rating:5, tags:["Beach","Culture","Surfing","Budget"], visa:"Free on Arrival", best:"Apr–Oct" },
  { name:"Vietnam", flag:"🇻🇳",
    img:"img/vietnam.jpg",
    continent:"Asia", desc:"Halong Bay, ancient Hoi An lanterns, motorbike culture and pho",
    price:500, rating:5, tags:["Culture","Food","Adventure","Budget"], visa:"eVisa", best:"Feb–Apr, Aug–Oct" },
  { name:"China", flag:"🇨🇳",
    img:"img/china.jpg",
    continent:"Asia", desc:"Great Wall, Forbidden City, giant pandas and billion-year-old landscapes",
    price:900, rating:4, tags:["Heritage","Culture","History","Nature"], visa:"Visa Required", best:"Apr–May, Sep–Oct" },
  { name:"Nepal", flag:"🇳🇵",
    img:"img/nepal.jpg",
    continent:"Asia", desc:"Everest Base Camp, Buddhist stupas and the world's highest peaks",
    price:600, rating:5, tags:["Trekking","Adventure","Spiritual","Budget"], visa:"Visa on Arrival", best:"Oct–Nov, Mar–May" },
  { name:"Sri Lanka", flag:"🇱🇰",
    img:"img/SriLanka.jpg",
    continent:"Asia", desc:"Tea estates, ancient ruins, elephants and stunning golden coastlines",
    price:500, rating:4, tags:["Nature","Heritage","Beach","Wildlife"], visa:"eVisa", best:"Dec–Mar" },
  { name:"Singapore", flag:"🇸🇬",
    img:"img/singapore.jpg",
    continent:"Asia", desc:"Futuristic skyline, hawker centres, Gardens by the Bay and Marina Bay Sands",
    price:1800, rating:5, tags:["Modern","Food","Shopping","Luxury"], visa:"Visa Free", best:"Feb–Apr" },
  { name:"South Korea", flag:"🇰🇷",
    img:"img/southkorea.jpg",
    continent:"Asia", desc:"K-pop culture, ancient palaces, BBQ feasts, cherry blossoms and neon Seoul",
    price:1200, rating:5, tags:["Culture","Food","K-pop","Modern"], visa:"Visa Free", best:"Apr–Jun, Sep–Nov" },
  { name:"Malaysia", flag:"🇲🇾",
    img:"img/malaysia.jpg",
    continent:"Asia", desc:"Petronas Towers, rainforest, diverse cuisine and Cameron Highlands",
    price:600, rating:4, tags:["Nature","Food","Culture","Budget"], visa:"Visa Free", best:"Mar–Oct" },
  { name:"Philippines", flag:"🇵🇭",
    img:"img/philippines.jpg",
    continent:"Asia", desc:"7,000+ islands, world-class diving, white sand beaches and warm smiles",
    price:700, rating:5, tags:["Beach","Diving","Islands","Budget"], visa:"Visa Free", best:"Dec–May" },
  { name:"Cambodia", flag:"🇰🇭",
    img:"img/cambodia.jpg",
    continent:"Asia", desc:"Angkor Wat, floating villages, jungle temples and resilient Khmer culture",
    price:400, rating:4, tags:["Heritage","Budget","History","Adventure"], visa:"eVisa", best:"Nov–Mar" },
  { name:"UAE", flag:"🇦🇪",
    img:"img/uae.jpg",
    continent:"Asia", desc:"Burj Khalifa, desert safaris, gold souks and luxury beyond imagination",
    price:2000, rating:5, tags:["Luxury","Modern","Desert","Shopping"], visa:"Visa on Arrival", best:"Nov–Mar" },
  { name:"Turkey", flag:"🇹🇷",
    img:"img/turkey.jpg",
    continent:"Asia", desc:"Cappadocia hot air balloons, Istanbul bazaars and turquoise Aegean coast",
    price:700, rating:5, tags:["Culture","History","Beach","Food"], visa:"eVisa", best:"Apr–Jun, Sep–Nov" },
  { name:"Jordan", flag:"🇯🇴",
    img:"img/jordan.jpg",
    continent:"Asia", desc:"Petra rose-red city, Wadi Rum desert, Dead Sea floating and Roman ruins",
    price:900, rating:5, tags:["Heritage","Desert","History","Adventure"], visa:"Visa on Arrival", best:"Mar–May, Sep–Nov" },
  { name:"Georgia", flag:"🇬🇪",
    img:"img/georgia.jpg",
    continent:"Asia", desc:"Caucasus mountains, ancient monasteries, wine country and Tbilisi charm",
    price:500, rating:5, tags:["Nature","Wine","Culture","Budget"], visa:"Visa Free", best:"May–Oct" },
  { name:"Uzbekistan", flag:"🇺🇿",
    img:"img/uzbekistan.jpg",
    continent:"Asia", desc:"Silk Road — Samarkand, Bukhara, Khiva and breathtaking blue-tiled mosques",
    price:500, rating:5, tags:["Heritage","History","Silk Road","Culture"], visa:"eVisa", best:"Apr–Jun, Sep–Nov" },
  { name:"Oman", flag:"🇴🇲",
    img:"img/oman.jpg",
    continent:"Asia", desc:"Dramatic fjords, rolling desert dunes, ancient forts and dolphin-rich coasts",
    price:900, rating:4, tags:["Desert","Culture","Adventure","Nature"], visa:"eVisa", best:"Oct–Mar" },
  { name:"Taiwan", flag:"🇹🇼",
    img:"img/taiwan.jpg",
    continent:"Asia", desc:"Night markets, hot springs, dramatic mountain gorges and bubble tea paradise",
    price:900, rating:5, tags:["Food","Culture","Nature","Modern"], visa:"Visa Free", best:"Oct–Apr" },
  { name:"Kazakhstan", flag:"🇰🇿",
    img:"img/kazakhstan.jpg",
    continent:"Asia", desc:"Vast steppes, Almaty mountains, Charyn Canyon and nomadic heritage",
    price:600, rating:4, tags:["Nature","Adventure","Culture","Vast"], visa:"Visa Free", best:"Jun–Sep" },
  { name:"Armenia", flag:"🇦🇲",
    img:"img/armenia.jpg",
    continent:"Asia", desc:"Ancient monasteries, Mount Ararat views, apricot orchards and rich wine",
    price:500, rating:4, tags:["History","Culture","Nature","Wine"], visa:"Visa Free", best:"May–Sep" },
  { name:"Pakistan", flag:"🇵🇰",
    img:"img/pakistan.jpg",
    continent:"Asia", desc:"K2 base camp, Lahore Mughal heritage, Hunza Valley and vibrant bazaars",
    price:400, rating:4, tags:["Adventure","Trekking","Heritage","Budget"], visa:"eVisa", best:"Apr–Oct" },
  { name:"Saudi Arabia", flag:"🇸🇦",
    img:"img/Saudiarabia.jpg",
    continent:"Asia", desc:"AlUla rock city, Red Sea diving and ancient Nabataean heritage sites",
    price:1200, rating:4, tags:["Heritage","Luxury","Desert","New"], visa:"eVisa", best:"Nov–Feb" },
  { name:"Russia", flag:"🇷🇺",
    img:"img/russia.jpg",
    continent:"Asia", desc:"Red Square, Lake Baikal, Trans-Siberian Railway and vast diverse landscapes",
    price:800, rating:4, tags:["History","Culture","Architecture","Nature"], visa:"Visa Required", best:"May–Sep" },
  { name:"Qatar", flag:"🇶🇦",
    img:"img/qatar.jpg",
    continent:"Asia", desc:"Futuristic Doha skyline, desert safaris, Souq Waqif and luxury hospitality",
    price:1500, rating:4, tags:["Modern","Luxury","Desert","Culture"], visa:"Visa Free", best:"Nov–Mar" },
  { name:"Israel", flag:"🇮🇱",
    img:"img/israel.jpg",
    continent:"Asia", desc:"Jerusalem holy sites, Dead Sea floating, Tel Aviv beaches and diverse culture",
    price:1300, rating:4, tags:["History","Culture","Beach","Heritage"], visa:"Visa Free", best:"Mar–May, Sep–Nov" },

  // ─── EUROPE ────────────────────────────────────────────
  { name:"France", flag:"🇫🇷",
    img:"img/france.jpg",
    continent:"Europe", desc:"Eiffel Tower, French Riviera, world-class cuisine, wine and Impressionist art",
    price:1500, rating:5, tags:["Culture","Food","Art","Romance"], visa:"Schengen", best:"Apr–Jun, Sep–Oct" },
  { name:"Italy", flag:"🇮🇹",
    img:"img/italy.jpg",
    continent:"Europe", desc:"Rome's Colosseum, Venetian canals, Amalfi Coast and pasta perfection",
    price:1400, rating:5, tags:["History","Food","Art","Luxury"], visa:"Schengen", best:"Apr–Jun, Sep–Oct" },
  { name:"Spain", flag:"🇪🇸",
    img:"img/spain.jpg",
    continent:"Europe", desc:"Sagrada Familia, flamenco dancing, tapas culture, beaches and La Tomatina",
    price:1200, rating:5, tags:["Culture","Beach","Food","Art"], visa:"Schengen", best:"Apr–Jun, Sep–Oct" },
  { name:"Greece", flag:"🇬🇷",
    img:"img/greece.jpg",
    continent:"Europe", desc:"Santorini sunsets, Acropolis of Athens, Aegean islands and ouzo nights",
    price:1100, rating:5, tags:["Beach","History","Islands","Romance"], visa:"Schengen", best:"May–Sep" },
  { name:"Portugal", flag:"🇵🇹",
    img:"img/portugal.jpg",
    continent:"Europe", desc:"Lisbon trams, Porto wine, Algarve sea cliffs and Age of Exploration heritage",
    price:1000, rating:5, tags:["Culture","Beach","Food","Budget"], visa:"Schengen", best:"May–Oct" },
  { name:"Switzerland", flag:"🇨🇭",
    img:"img/switzerland.jpg",
    continent:"Europe", desc:"Swiss Alps, luxury watches, pristine lakes, ski resorts and finest chocolate",
    price:3000, rating:5, tags:["Alps","Luxury","Skiing","Nature"], visa:"Schengen", best:"Jun–Sep, Dec–Mar" },
  { name:"Germany", flag:"🇩🇪",
    img:"img/germany.jpg",
    continent:"Europe", desc:"Neuschwanstein Castle, Oktoberfest, Rhine Valley and Berlin's vibrant arts scene",
    price:1300, rating:5, tags:["History","Beer","Culture","Modern"], visa:"Schengen", best:"May–Sep" },
  { name:"Netherlands", flag:"🇳🇱",
    img:"img/netherlands.jpg",
    continent:"Europe", desc:"Tulip fields, windmills, Amsterdam canals and world-class Rijksmuseum",
    price:1400, rating:4, tags:["Culture","Cycling","Art","History"], visa:"Schengen", best:"Apr–May, Jun–Aug" },
  { name:"Austria", flag:"🇦🇹",
    img:"img/austria.jpg",
    continent:"Europe", desc:"Vienna opera houses, Habsburg palaces, Sound of Music Alps and Schnitzel",
    price:1500, rating:5, tags:["Culture","Music","Alps","History"], visa:"Schengen", best:"Jun–Sep, Dec–Mar" },
  { name:"Czech Republic", flag:"🇨🇿",
    img:"img/czechrepublic.jpg",
    continent:"Europe", desc:"Prague's fairytale old town, craft beer culture and Bohemian countryside",
    price:900, rating:5, tags:["Culture","Beer","History","Budget"], visa:"Schengen", best:"May–Sep" },
  { name:"Iceland", flag:"🇮🇸",
    img:"img/iceland.jpg",
    continent:"Europe", desc:"Northern Lights, geysers, waterfalls, lava fields and summer midnight sun",
    price:2200, rating:5, tags:["Nature","Adventure","Aurora","Unique"], visa:"Schengen", best:"Jun–Aug, Nov–Feb" },
  { name:"Norway", flag:"🇳🇴",
    img:"img/norway.jpg",
    continent:"Europe", desc:"Dramatic fjords, Viking heritage, Northern Lights and midnight sun adventures",
    price:2500, rating:5, tags:["Nature","Fjords","Aurora","Adventure"], visa:"Schengen", best:"Jun–Aug, Nov–Feb" },
  { name:"Sweden", flag:"🇸🇪",
    img:"img/sweden.jpg",
    continent:"Europe", desc:"Stockholm archipelago, Lapland reindeer, ABBA and Swedish design culture",
    price:2000, rating:4, tags:["Nature","Culture","Modern","Aurora"], visa:"Schengen", best:"Jun–Aug, Dec–Feb" },
  { name:"UK", flag:"🇬🇧",
    img:"img/UK.jpg",
    continent:"Europe", desc:"London landmarks, Scottish Highlands, Welsh castles and Fish & Chips culture",
    price:1800, rating:5, tags:["Culture","History","Royal","Modern"], visa:"eVisa", best:"May–Sep" },
  { name:"Ireland", flag:"🇮🇪",
    img:"img/ireland.jpg",
    continent:"Europe", desc:"Green Cliffs of Moher, medieval castles, pubs alive with traditional music",
    price:1600, rating:4, tags:["Nature","Culture","Beer","History"], visa:"Visa Required", best:"May–Sep" },
  { name:"Croatia", flag:"🇭🇷",
    img:"img/croatia.jpg",
    continent:"Europe", desc:"Dubrovnik's medieval walls, Plitvice lakes, Adriatic islands and Game of Thrones sets",
    price:1100, rating:5, tags:["Beach","History","Islands","Nature"], visa:"Schengen", best:"Jun–Sep" },
  { name:"Hungary", flag:"🇭🇺",
    img:"img/Hungary.jpg",
    continent:"Europe", desc:"Budapest thermal baths, ruin bars, Danube panorama and goulash soup",
    price:800, rating:5, tags:["Culture","Spa","Food","Budget"], visa:"Schengen", best:"Apr–Oct" },
  { name:"Poland", flag:"🇵🇱",
    img:"img/poland.jpg",
    continent:"Europe", desc:"Krakow's stunning old town, Auschwitz memorial, Warsaw revival and pierogi",
    price:700, rating:4, tags:["History","Budget","Culture","Food"], visa:"Schengen", best:"May–Sep" },
  { name:"Romania", flag:"🇷🇴",
    img:"img/romania.jpg",
    continent:"Europe", desc:"Dracula's Transylvania, painted monasteries, Carpathian mountains and charm",
    price:600, rating:4, tags:["History","Budget","Nature","Culture"], visa:"Schengen", best:"May–Sep" },
  { name:"Montenegro", flag:"🇲🇪",
    img:"img/montenegro.jpg",
    continent:"Europe", desc:"Bay of Kotor, Durmitor peaks, Adriatic beaches and medieval old towns",
    price:700, rating:5, tags:["Beach","Nature","History","Budget"], visa:"Visa Free", best:"Jun–Sep" },
  { name:"Slovenia", flag:"🇸🇮",
    img:"img/slovenia.jpg",
    continent:"Europe", desc:"Lake Bled perfection, Triglav peaks, charming Ljubljana and Postojna caves",
    price:900, rating:5, tags:["Nature","Budget","Adventure","Romance"], visa:"Schengen", best:"Jun–Sep" },
  { name:"Malta", flag:"🇲🇹",
    img:"img/malta.jpg",
    continent:"Europe", desc:"Azure Window, Valletta UNESCO city, diving and medieval Knights history",
    price:1100, rating:5, tags:["Beach","History","Diving","Islands"], visa:"Schengen", best:"Apr–Jun, Sep–Oct" },
  { name:"Finland", flag:"🇫🇮",
    img:"img/finland.jpg",
    continent:"Europe", desc:"Sauna culture, Santa Claus Village, Northern Lights and 180,000 lakes",
    price:2000, rating:4, tags:["Nature","Aurora","Sauna","Unique"], visa:"Schengen", best:"Jun–Aug, Dec–Mar" },
  { name:"Denmark", flag:"🇩🇰",
    img:"img/denmark.jpg",
    continent:"Europe", desc:"Happiest nation, LEGO birthplace, The Little Mermaid and world's best dining",
    price:2200, rating:5, tags:["Culture","Food","Modern","Cycling"], visa:"Schengen", best:"May–Aug" },
  { name:"Albania", flag:"🇦🇱",
    img:"img/albania.jpg",
    continent:"Europe", desc:"Albanian Riviera beaches, Ottoman bazaars and Europe's most affordable secret",
    price:400, rating:4, tags:["Beach","Budget","Hidden Gem","Nature"], visa:"Visa Free", best:"Jun–Sep" },
  { name:"Belgium", flag:"🇧🇪",
    img:"img/belgium.jpg",
    continent:"Europe", desc:"Medieval Bruges, grand squares, world-class chocolates, waffles and Trappist beer",
    price:1300, rating:4, tags:["Culture","Food","History","Beer"], visa:"Schengen", best:"Apr–Oct" },
  { name:"Monaco", flag:"🇲🇨",
    img:"img/monaco.jpg",
    continent:"Europe", desc:"Monte Carlo Casino, Formula 1 heritage, ultra-yachts and Riviera luxury",
    price:4000, rating:5, tags:["Luxury","Modern","Coastal","Exclusive"], visa:"Schengen", best:"May–Sep" },

  // ─── AFRICA ────────────────────────────────────────────
  { name:"Morocco", flag:"🇲🇦",
    img:"img/morocco.jpg",
    continent:"Africa", desc:"Marrakech souks, Sahara dunes, blue Chefchaouen and fragrant tagine",
    price:600, rating:5, tags:["Culture","Desert","Food","History"], visa:"Visa Free", best:"Mar–May, Sep–Nov" },
  { name:"Egypt", flag:"🇪🇬",
    img:"img/egypt.jpg",
    continent:"Africa", desc:"Pyramids of Giza, Nile cruises, Valley of the Kings and Red Sea coral reefs",
    price:700, rating:5, tags:["History","Desert","Diving","Ancient"], visa:"Visa on Arrival", best:"Oct–Apr" },
  { name:"South Africa", flag:"🇿🇦",
    img:"img/southafrica.jpg",
    continent:"Africa", desc:"Big Five safari, Table Mountain, Cape Winelands and the iconic Garden Route",
    price:1000, rating:5, tags:["Safari","Nature","Adventure","Wine"], visa:"Visa Free", best:"May–Sep" },
  { name:"Kenya", flag:"🇰🇪",
    img:"img/kenya.jpg",
    continent:"Africa", desc:"Great Wildebeest Migration in Maasai Mara, Amboseli and safari paradise",
    price:1200, rating:5, tags:["Safari","Wildlife","Adventure","Nature"], visa:"eVisa", best:"Jul–Oct, Jan–Feb" },
  { name:"Tanzania", flag:"🇹🇿",
    img:"img/tanzania.jpg",
    continent:"Africa", desc:"Kilimanjaro summit, Serengeti plains, Zanzibar beaches and Ngorongoro crater",
    price:1500, rating:5, tags:["Safari","Trekking","Beach","Wildlife"], visa:"eVisa", best:"Jun–Oct, Jan–Feb" },
  { name:"Rwanda", flag:"🇷🇼",
    img:"img/rwanda.jpg",
    continent:"Africa", desc:"Mountain gorilla trekking, Volcanoes National Park and Africa's cleanest city",
    price:1500, rating:5, tags:["Gorillas","Wildlife","Nature","Luxury"], visa:"Visa on Arrival", best:"Jun–Sep, Dec–Feb" },
  { name:"Namibia", flag:"🇳🇦",
    img:"img/namibia.jpg",
    continent:"Africa", desc:"Sossusvlei red dunes, Etosha elephants, Skeleton Coast and star-filled skies",
    price:1400, rating:5, tags:["Desert","Safari","Photography","Nature"], visa:"Visa Free", best:"May–Sep" },
  { name:"Seychelles", flag:"🇸🇨",
    img:"img/seychelles.jpg",
    continent:"Africa", desc:"Vallée de Mai coco de mer palms, granite beaches and the clearest ocean on Earth",
    price:3500, rating:5, tags:["Beach","Luxury","Honeymoon","Diving"], visa:"Visa Free", best:"Apr–May, Oct–Nov" },
  { name:"Ethiopia", flag:"🇪🇹",
    img:"img/ethiopia.jpg",
    continent:"Africa", desc:"Lalibela rock-hewn churches, ancient Axum obelisks and birthplace of coffee",
    price:500, rating:4, tags:["Heritage","Coffee","Trekking","Culture"], visa:"eVisa", best:"Oct–Mar" },
  { name:"Zimbabwe", flag:"🇿🇼",
    img:"img/zimbabwe.jpg",
    continent:"Africa", desc:"Victoria Falls thunder, Hwange National Park lions and ancient Great Zimbabwe",
    price:900, rating:4, tags:["Nature","Safari","Heritage","Adventure"], visa:"Visa on Arrival", best:"May–Oct" },
  { name:"Botswana", flag:"🇧🇼",
    img:"img/botswana.jpg",
    continent:"Africa", desc:"Okavango Delta mokoro rides, Chobe's massive elephant herds and exclusive lodges",
    price:2500, rating:5, tags:["Safari","Luxury","Wildlife","Unique"], visa:"Visa Free", best:"May–Oct" },
  { name:"Madagascar", flag:"🇲🇬",
    img:"img/madagascar.jpg",
    continent:"Africa", desc:"Baobab Alley, unique lemurs, limestone tsingy and pristine coral reefs",
    price:1000, rating:5, tags:["Wildlife","Nature","Unique","Adventure"], visa:"Visa on Arrival", best:"Jun–Sep, Dec–Mar" },
  { name:"Mauritius", flag:"🇲🇺",
    img:"img/mauritius.jpg",
    continent:"Africa", desc:"Turquoise lagoon beaches, underwater waterfall illusion, rum and diverse culture",
    price:2000, rating:5, tags:["Beach","Luxury","Honeymoon","Diving"], visa:"Visa Free", best:"May–Dec" },
  { name:"Tunisia", flag:"🇹🇳",
    img:"img/tunisia.jpg",
    continent:"Africa", desc:"Carthage ruins, Star Wars Tatooine sets, Medina markets and turquoise coast",
    price:500, rating:4, tags:["History","Budget","Beach","Desert"], visa:"Visa Free", best:"Apr–Jun, Sep–Oct" },
  { name:"Mozambique", flag:"🇲🇿",
    img:"img/mozambique.jpg",
    continent:"Africa", desc:"Bazaruto Archipelago, whale sharks, Portuguese charm and dhow sailing",
    price:900, rating:4, tags:["Beach","Diving","Nature","Unique"], visa:"eVisa", best:"Apr–Nov" },
  { name:"Senegal", flag:"🇸🇳",
    img:"img/senegal.jpg",
    continent:"Africa", desc:"Vibrant Dakar, Goree Island history, pink Lake Retba and lively music culture",
    price:700, rating:4, tags:["Culture","History","Music","Beach"], visa:"Visa Free", best:"Nov–May" },
  { name:"Uganda", flag:"🇺🇬",
    img:"img/uganda.jpg",
    continent:"Africa", desc:"Mountain gorillas, source of the Nile, Queen Elizabeth wildlife and lush nature",
    price:1200, rating:5, tags:["Nature","Gorillas","Safari","Adventure"], visa:"eVisa", best:"Jun–Sep, Dec–Feb" },

  // ─── NORTH AMERICA ─────────────────────────────────────
  { name:"USA", flag:"🇺🇸",
    img:"img/USA.jpg",
    continent:"North America", desc:"New York, Grand Canyon, Hollywood, Yellowstone and legendary road trips",
    price:2000, rating:5, tags:["Diverse","Culture","Nature","Modern"], visa:"ESTA", best:"Year-round" },
  { name:"Canada", flag:"🇨🇦",
    img:"img/canada.jpg",
    continent:"North America", desc:"Banff glaciers, Niagara Falls, maple syrup, hockey and Northern Lights",
    price:1800, rating:5, tags:["Nature","Adventure","Wildlife","Aurora"], visa:"eTA", best:"Jun–Sep, Dec–Mar" },
  { name:"Mexico", flag:"🇲🇽",
    img:"img/mexico.jpg",
    continent:"North America", desc:"Mayan pyramids, Cancún beaches, tacos, tequila and Dia de los Muertos",
    price:800, rating:5, tags:["Culture","Beach","Food","History"], visa:"Visa Free", best:"Dec–Apr" },
  { name:"Cuba", flag:"🇨🇺",
    img:"img/cuba.jpg",
    continent:"North America", desc:"Classic 1950s cars, salsa nights, Havana cigars and untouched beaches",
    price:700, rating:4, tags:["Culture","Music","Beach","Unique"], visa:"Tourist Card", best:"Nov–Apr" },
  { name:"Costa Rica", flag:"🇨🇷",
    img:"img/costarica.jpg",
    continent:"North America", desc:"Pura Vida lifestyle, sloths, zip-lining, volcanoes and eco-lodges",
    price:1000, rating:5, tags:["Nature","Adventure","Wildlife","Eco"], visa:"Visa Free", best:"Dec–Apr" },
  { name:"Jamaica", flag:"🇯🇲",
    img:"img/jamaica.jpg",
    continent:"North America", desc:"Reggae birthplace, Bob Marley, Negril 7-mile beach and Blue Mountains",
    price:900, rating:4, tags:["Beach","Music","Culture","Food"], visa:"Visa Free", best:"Nov–Apr" },
  { name:"Guatemala", flag:"🇬🇹",
    img:"img/guatemala.jpg",
    continent:"North America", desc:"Tikal Mayan pyramids, Lake Atitlán volcanoes and colourful Mayan villages",
    price:500, rating:4, tags:["Heritage","Nature","Budget","Adventure"], visa:"Visa Free", best:"Nov–Apr" },
  { name:"Panama", flag:"🇵🇦",
    img:"img/panama.jpg",
    continent:"North America", desc:"Famous Canal, San Blas islands, cloud forest and incredible biodiversity",
    price:900, rating:4, tags:["Nature","Islands","History","Adventure"], visa:"Visa Free", best:"Dec–Apr" },
  { name:"Belize", flag:"🇧🇿",
    img:"img/belize.jpg",
    continent:"North America", desc:"Great Blue Hole diving, barrier reef, jungle ruins and Caribbean vibes",
    price:900, rating:5, tags:["Diving","Nature","Beach","Adventure"], visa:"Visa Free", best:"Nov–May" },
  { name:"Dominican Republic", flag:"🇩🇴",
    img:"img/dominican.jpg",
    continent:"North America", desc:"Punta Cana all-inclusives, merengue music, waterfalls and rum cocktails",
    price:1000, rating:4, tags:["Beach","Resort","Music","Budget"], visa:"E-Ticket", best:"Nov–Apr" },
  { name:"Bahamas", flag:"🇧🇸",
    img:"img/bahamas.jpg",
    continent:"North America", desc:"Swimming pigs, crystal Caribbean waters, coral reefs and island paradise",
    price:1500, rating:5, tags:["Beach","Luxury","Islands","Diving"], visa:"Visa Free", best:"Dec–Apr" },
  { name:"Barbados", flag:"🇧🇧",
    img:"img/barbados.jpg",
    continent:"North America", desc:"Rum distilleries, surf spots, colonial history and perfect tropical beaches",
    price:1200, rating:4, tags:["Beach","Culture","Food","Surfing"], visa:"Visa Free", best:"Dec–Apr" },

  // ─── SOUTH AMERICA ─────────────────────────────────────
  { name:"Brazil", flag:"🇧🇷",
    img:"img/brazil.jpg",
    continent:"South America", desc:"Rio Carnival, Amazon rainforest, Iguaçú Falls and Copacabana beach",
    price:900, rating:5, tags:["Nature","Culture","Beach","Adventure"], visa:"Visa Free", best:"Dec–Mar" },
  { name:"Peru", flag:"🇵🇪",
    img:"img/peru.jpg",
    continent:"South America", desc:"Machu Picchu wonder, Inca Trail, Lake Titicaca and ceviche perfection",
    price:800, rating:5, tags:["Heritage","Trekking","History","Nature"], visa:"Visa Free", best:"May–Sep" },
  { name:"Argentina", flag:"🇦🇷",
    img:"img/argentina.jpg",
    continent:"South America", desc:"Buenos Aires tango, Patagonia wilderness, Mendoza wine and Perito Moreno glacier",
    price:800, rating:5, tags:["Culture","Nature","Wine","Adventure"], visa:"Visa Free", best:"Oct–Apr" },
  { name:"Colombia", flag:"🇨🇴",
    img:"img/colombia.jpg",
    continent:"South America", desc:"Cartagena's colourful walls, Medellín innovation, coffee region and salsa nights",
    price:700, rating:5, tags:["Culture","Coffee","Food","History"], visa:"Visa Free", best:"Dec–Mar, Jul–Aug" },
  { name:"Chile", flag:"🇨🇱",
    img:"img/chile.jpg",
    continent:"South America", desc:"Atacama Desert, Torres del Paine, Easter Island statues and Patagonian fjords",
    price:1000, rating:5, tags:["Nature","Adventure","Trekking","Unique"], visa:"Visa Free", best:"Nov–Mar" },
  { name:"Ecuador", flag:"🇪🇨",
    img:"img/ecuador.jpg",
    continent:"South America", desc:"Galápagos Islands wildlife, Amazon rainforest, Quito and the equator line",
    price:800, rating:5, tags:["Wildlife","Nature","Unique","Adventure"], visa:"Visa Free", best:"Jun–Sep, Dec–Feb" },
  { name:"Bolivia", flag:"🇧🇴",
    img:"img/bolivia.jpg",
    continent:"South America", desc:"Salar de Uyuni salt flats, Death Road cycling, Amazon jungle and Andean culture",
    price:400, rating:4, tags:["Adventure","Nature","Budget","Unique"], visa:"Visa Free", best:"May–Oct" },
  { name:"Uruguay", flag:"🇺🇾",
    img:"img/uruguay.jpg",
    continent:"South America", desc:"Montevideo culture, Punta del Este glamour, estancias and mate rituals",
    price:900, rating:4, tags:["Culture","Beach","Food","Wine"], visa:"Visa Free", best:"Dec–Mar" },
  { name:"Venezuela", flag:"🇻🇪",
    img:"img/venezuela.jpg",
    continent:"South America", desc:"Angel Falls — world's highest waterfall, Los Roques islands and tepuis",
    price:300, rating:3, tags:["Nature","Adventure","Unique","Budget"], visa:"Visa Free", best:"Dec–Apr" },
  { name:"Paraguay", flag:"🇵🇾",
    img:"img/paraguay.jpg",
    continent:"South America", desc:"Jesuit missions, Itaipú dam, Chaco wilderness and authentic South America",
    price:350, rating:3, tags:["Budget","History","Nature","Off-Beaten"], visa:"Visa Free", best:"Apr–Sep" },

  // ─── OCEANIA ───────────────────────────────────────────
  { name:"Australia", flag:"🇦🇺",
    img:"img/australia.jpg",
    continent:"Oceania", desc:"Great Barrier Reef, Sydney Opera House, Outback, kangaroos and surf culture",
    price:2200, rating:5, tags:["Nature","Wildlife","Beach","Adventure"], visa:"eVisa", best:"Sep–Nov, Mar–May" },
  { name:"New Zealand", flag:"🇳🇿",
    img:"img/newzealand.jpg",
    continent:"Oceania", desc:"Hobbiton, fjordland beauty, bungee jumping birthplace and Maori culture",
    price:2000, rating:5, tags:["Nature","Adventure","LOTR","Wildlife"], visa:"NZeTA", best:"Dec–Feb, Jun–Aug" },
  { name:"Fiji", flag:"🇫🇯",
    img:"img/fiji.jpg",
    continent:"Oceania", desc:"Coral coast, overwater bures, kava ceremonies, diving and warm Pacific culture",
    price:1800, rating:5, tags:["Beach","Luxury","Diving","Honeymoon"], visa:"Visa Free", best:"May–Oct" },
  { name:"Papua New Guinea", flag:"🇵🇬",
    img:"img/papuanew.jpg",
    continent:"Oceania", desc:"Tribal cultures, pristine coral reefs, bird of paradise and unexplored jungles",
    price:1500, rating:4, tags:["Adventure","Wildlife","Culture","Unique"], visa:"Visa on Arrival", best:"May–Oct" },
  { name:"Vanuatu", flag:"🇻🇺",
    img:"img/vanuatu.jpg",
    continent:"Oceania", desc:"Active volcanoes you can approach, blue holes, pristine reefs and Pacific culture",
    price:1400, rating:4, tags:["Adventure","Nature","Diving","Unique"], visa:"Visa Free", best:"Apr–Oct" },
  { name:"Tonga", flag:"🇹🇴",
    img:"img/tonga.jpg",
    continent:"Oceania", desc:"Swim with humpback whales, pristine coral atolls and authentic Polynesian royal culture",
    price:1400, rating:5, tags:["Wildlife","Diving","Unique","Nature"], visa:"Visa Free", best:"Jun–Nov" },
  { name:"Samoa", flag:"🇼🇸",
    img:"img/samoa.jpg",
    continent:"Oceania", desc:"To Sua ocean trench, rainforest trails, fa'a Samoa culture and pristine lagoons",
    price:1300, rating:4, tags:["Culture","Nature","Beach","Unique"], visa:"Visa on Arrival", best:"May–Oct" },
  { name:"Palau", flag:"🇵🇼",
    img:"img/palau.jpg",
    continent:"Oceania", desc:"Jellyfish lake, Rock Islands, world-class diving and pristine marine life",
    price:1800, rating:5, tags:["Diving","Nature","Islands","Unique"], visa:"Visa on Arrival", best:"Nov–Apr" },

  // ─── ANTARCTICA ────────────────────────────────────────
  { name:"Antarctica", flag:"🇦🇶",
    img:"img/antarctica.jpg",
    continent:"Antarctica", desc:"The last frontier — penguins, icebergs, aurora australis and absolute wilderness",
    price:8000, rating:5, tags:["Extreme","Wildlife","Unique","Bucket List"], visa:"Permit Required", best:"Nov–Mar" },
];